### ISSUE TITLE
Use scroll-mpt sync fullnode BlobClients: failed to get blob by versioned hash from BlobClient

### ISSUE THREAD

**Issue by orange723** [scroll-tech/go-ethereum#1181]
snapshot link https://scroll-geth-snapshot.s3.us-west-2.amazonaws.com/mpt/latest.tar

I download new snapshot and start node

But log output this warning, I possible ignore this problem ?

container log is 

```
node-1  | WARN [05-06|08:22:53.313] BlobClients: failed to get blob by versioned hash from BlobClient err="error while fetching blob, message: , code: , versioned hash: 0x012889afb7d14a0e63d529f5c02f3b2128cdca453df2d53a1e5791523c6d6b9b" blob client pos in BlobClients=2
node-1  | WARN [05-06|08:22:53.324] BlobClients: failed to get blob by versioned hash from BlobClient err="failed to decode result into struct, err: invalid character 'T' looking for beginning of value" blob client pos in BlobClients=0
node-1  | WARN [05-06|08:22:53.325] BlobClients: failed to get blob by versioned hash from BlobClient err="missing blob 0x012889afb7d14a0e63d529f5c02f3b2128cdca453df2d53a1e5791523c6d6b9b in slot 8961219" blob client pos in BlobClients=1
node-1  | WARN [05-06|08:22:53.325] syncing pipeline step failed due to temporary error, retrying err="temporary: failed to process rollup events to DA, error: failed to get and append commit batch DA: failed to get commit batch da: 171174, err: failed to decode DA, batch index: 171174, err: failed to fetch blob from blob client, err: temporary: BlobClients.GetBlobByVersionedHash: failed to get blob by versioned hash from all BlobClients"
```

this is my compose file

```
services:
    node:
        image: scrolltech/l2geth:scroll-v5.8.38
        restart: always
        stop_grace_period: 30s
        volumes:
            - ./data/:/volume/
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 0.0.0.0:8545:8545
            - 0.0.0.0:6060:6060
            - 0.0.0.0:30303:30303
            - 0.0.0.0:30303:30303/udp
        environment:
            - RUST_LOG=info
            - CHAIN_ID=534352
        command:
        - --scroll
        - --datadir=/volume
        - --gcmode=archive
        - --syncmode=full
        - --cache.noprefetch
        - --http
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --http.corsdomain=*
        - --http.port=8545
        - --http.api=eth,net,web3,debug,scroll
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=eth,net,web3,debug,scroll
        - --ws.origins=*
        - --metrics
        - --metrics.addr=0.0.0.0
        - --metrics.port=6060
        - --port=30303
        - --txlookuplimit=0
        - --scroll-mpt
        - --da.sync
        - --rollup.verify
        - --l1.endpoint=http://xxxxx
        - --da.blob.beaconnode=http://xxxxxx
        - --da.blob.blobscan=https://api.blobscan.com/blobs/
        - --da.blob.blocknative=https://api.ethernow.xyz/v1/blob/
        - --cache.snapshot=0
        - --snapshot=false
```
