### ISSUE TITLE
Scroll mainnet DA sync is always out of sync

### ISSUE THREAD

**Issue by mmd-afegbua** [scroll-tech/go-ethereum#1198]
#### System information

Geth version: `v5.8.52`
OS & Version: Linux

#### Expected behaviour
Scroll node is in sync, especially with the recent increase of blocktime from 3 seconds to 1 second.

#### Actual behaviour
Node gets stuck in one block for ~3 hours, then jumps 2,000+ blocks. After which it gets stuck at the new block for another three hours.

#### Steps to reproduce the behaviour
docker-compose.yml
```
services:
  geth:
    image: scrolltech/l2geth:scroll-v5.8.52
    command:
    - --scroll
    - --gcmode=archive
    - --syncmode=full
    - --scroll-mpt
    - --cache.noprefetch
    - --http
    - --http.addr=0.0.0.0
    - --http.vhosts=*
    - --http.corsdomain=*
    - --http.port=63435
    - --http.api=eth,net,web3,debug,scroll
    - --port=30303
    - --txlookuplimit=0
    - --l1.endpoint=https://eth-mainnet.rpc.x.superfluid.dev
    - --da.sync
    - --da.blob.blobscan=https://api.blobscan.com/blobs/
    - --da.blob.blocknative=https://api.ethernow.xyz/v1/blob/
    - --da.blob.beaconnode=http://9190.buck2.x.superfluid.dev
    - --cache.snapshot=0
    - --snapshot=false
    - --gpo.maxprice=500000000
    - --gpo.congestionthreshold=1000

    volumes:
      - ./geth_data:/root
      - ./config:/config
    ports:
      - "127.0.0.1:63435:63435"  # HTTP-RPC
      - "63436:30303"            # P2P
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "24G"
    logging:
      driver: "json-file"
      options:
        labels: "geth"
        env: "geth"
        compress: "true"
        max-size: "10m"
        max-file: "3"
```

#### Backtrace
The logs shows a timeline of over 15 minutes, block height remains at `16,322,906` and it has been the same for two hours.

````
geth_1  | WARN [06-09|10:52:29.469] Served eth_getBlockByNumber              conn=172.24.0.1:60942 reqid=1956194152 t="86.838µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:52:29.696] Served eth_getBlockByNumber              conn=172.24.0.1:60970 reqid=1956194152 t="58.584µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:52:59.477] Served eth_getBlockByNumber              conn=172.24.0.1:55668 reqid=1436062873 t="71.458µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:52:59.655] Served eth_getBlockByNumber              conn=172.24.0.1:55682 reqid=1436062873 t="53.564µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | INFO [06-09|10:53:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|10:54:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|10:55:02.201] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|10:56:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|10:57:02.201] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|10:58:02.201] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | WARN [06-09|10:58:29.549] Served eth_getBlockByNumber              conn=172.24.0.1:38332 reqid=1816079766 t="42.202µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:58:29.809] Served eth_getBlockByNumber              conn=172.24.0.1:46498 reqid=1816079766 t="64.585µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:58:59.466] Served eth_getBlockByNumber              conn=172.24.0.1:58252 reqid=1758050500 t="67.18µs"   err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:58:59.847] Served eth_getBlockByNumber              conn=172.24.0.1:58604 reqid=1758050500 t="60.297µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | INFO [06-09|10:59:02.201] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | WARN [06-09|10:59:29.473] Served eth_getBlockByNumber              conn=172.24.0.1:46220 reqid=1529232461 t="52.982µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:59:29.722] Served eth_getBlockByNumber              conn=172.24.0.1:46224 reqid=1529232461 t="65.296µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|10:59:59.480] Served eth_getBlockByNumber              conn=172.24.0.1:51646 reqid=1045241393 t="40.92µs"   err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | INFO [06-09|11:00:02.201] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|11:01:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|11:02:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|11:03:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|11:04:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | WARN [06-09|11:05:00.281] Served eth_getBlockByNumber              conn=172.24.0.1:60348 reqid=1841862183 t="59.585µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | INFO [06-09|11:05:02.201] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | WARN [06-09|11:05:29.476] Served eth_getBlockByNumber              conn=172.24.0.1:35962 reqid=850127865  t="34.337µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|11:05:30.350] Served eth_getBlockByNumber              conn=172.24.0.1:37804 reqid=850127865  t="50.598µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|11:05:59.471] Served eth_getBlockByNumber              conn=172.24.0.1:33720 reqid=878808395  t="65.697µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | WARN [06-09|11:06:00.560] Served eth_getBlockByNumber              conn=172.24.0.1:43588 reqid=878808395  t="57.772µs"  err="sync L1 finalized batch feature not enabled, cannot query L2 finalized block height"
geth_1  | INFO [06-09|11:06:02.203] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
geth_1  | INFO [06-09|11:07:02.202] L1 sync progress                         blockchain height=16,322,906 block hash=0x83df6bcd7124bfd2f769bd614e15365d11096ecad7463336a6a3604a11ab507d
````
